namespace LoadView
{
    // Single source of truth for the version string and the changelog shown in About.
    internal static class AppInfo
    {
        public const string Name = "LoadView";
        public const string Version = "3.0.2";
        public const string RepoUrl = "https://github.com/Jimmy20/LoadView";

        public static readonly string[] Changelog = new string[]
        {
            "3.0.2",
            "  - Fix: Fans now sits below Temperatures, as intended. 3.0.0 inserted the two",
            "    new sections in reverse, and an existing layout of clock/Fans/Temperatures",
            "    is corrected once on load",
            "",
            "3.0.1",
            "  - Fix: the note in the Settings footer was cut off mid-sentence where the",
            "    OK button starts",
            "  - The 3.0.0 list below was missing the theme, which did ship in 3.0.0",
            "",
            "3.0.0",
            "  - New: Theme choice - Follow system (default), Dark or Light. Follow system",
            "    tracks the Windows app theme and switches while running; clock/date colours",
            "    you never picked yourself move to ones that suit the new background",
            "  - New section: Temperatures, as labelled tiles under the clock. Covers CPU,",
            "    GPU and every disk that reports one - disks need no driver at all",
            "  - New section: Fans (RPM), for machines whose motherboard exposes them",
            "    (needs the sensor driver plus its own switch; many laptops expose none)",
            "  - Both sections are fully configurable: pick which components to show and",
            "    in what order, set tile and text sizes. A section with nothing to show",
            "    hides itself instead of leaving an empty frame",
            "  - Temperatures are no longer squeezed onto the CPU/GPU graph headers",
            "  - Settings rearranged into eight pages, one subject each: graph height sits",
            "    with the graphs, the NET colours with the NET graph, IP options together",
            "  - Clearer settings: unit choices instead of ambiguous checkboxes, Auto/Alert",
            "    checkboxes instead of \"0 means off\", tooltips throughout",
            "  - Fix: switching the hot-temperature highlight off no longer comes back as",
            "    \"red from 30 C\" after a restart",
            "",
            "2.11.0",
            "  - Security: a DLL dropped next to LoadView.exe is no longer loaded. Portable",
            "    exes often live in writable folders, and Windows searches there first",
            "  - Security: the country lookup can no longer steer where the flag file is",
            "    written, replies from web services are size-capped, and downloads no",
            "    longer offer Windows credentials to the server they talk to",
            "  - Security: the CPU-temp setup verifies the driver installer's certificate",
            "    exactly (a look-alike name used to pass) and checks a supplied file before",
            "    copying it anywhere",
            "  - Fix: a hand-edited settings.ini can no longer crash the app on startup",
            "  - Fix: helper commands can no longer hang forever instead of timing out",
            "  - Lower idle cost: fewer allocations per second in the GPU and graph code,",
            "    and less disk polling by both the overlay and the temperature reader",
            "",
            "2.10.1",
            "  - Security fix: the one-time setup now empties its folders before using",
            "    them. A file left there beforehand could be a hard link, and the",
            "    system-rights reader would have written through it into the linked file",
            "  - The PawnIO installer is now also checked against a pinned SHA-256, not",
            "    only its signature",
            "  - CPU temp ignores 'Distance to TjMax' sensors (headroom, not temperature)",
            "    and the log records every sensor found plus which one was used",
            "",
            "2.10.0",
            "  - Accurate CPU temp now works when your Windows account is NOT an",
            "    administrator: the reader runs as the SYSTEM account, so it can read",
            "    the sensor (before, it silently stayed blank on managed/company PCs)",
            "  - The one-time setup now stages the reader into an admin-only folder and",
            "    locks down every file it creates, so the elevated task cannot be abused",
            "  - PawnIO download is version-pinned and the signer is verified",
            "  - New: LoadView.exe --temp-remove undoes the whole setup",
            "",
            "2.9.1",
            "  - Refresh WAN now uses a fresh connection, so the public IP updates",
            "    correctly after a VPN / network change (no stale keep-alive route)",
            "",
            "2.9.0",
            "  - Right-click menu: \"Refresh WAN now\" (re-fetch the public IP on demand)",
            "  - Optional country name + flag under the WAN IP (Settings > Network),",
            "    off by default; looks up the country and downloads a small flag image",
            "",
            "2.8.0",
            "  - Accurate CPU temp now works with Windows Memory Integrity (HVCI) on:",
            "    uses the free, signed PawnIO driver instead of the blocked WinRing0",
            "  - One-click setup from Settings: installs PawnIO (one UAC) + a scheduled",
            "    task, so afterwards the temp starts silently with no more UAC prompts",
            "  - Right-click menu: added \"Contact me\" (opens your email client)",
            "",
            "2.7.0",
            "  - Optional accurate CPU temperature via a helper driver (off by default):",
            "    downloaded only when enabled, runs elevated, reports the true core temp;",
            "    the default app stays a driver-free, no-admin single exe",
            "",
            "2.6.0",
            "  - GPU temperature now works on NVIDIA, AMD and Intel (user-mode, no driver),",
            "    across all GPUs (takes the hottest); no admin required",
            "  - Temperature settings: °C/°F, show/hide CPU & GPU temp, red 'hot' threshold",
            "",
            "2.5.2",
            "  - CPU % now matches Task Manager (uses % Processor Time, not the",
            "    frequency-scaled % Processor Utility that overshot on turbo CPUs)",
            "",
            "2.5.1",
            "  - Fix false 100% CPU after waking from sleep/hibernation",
            "",
            "2.5.0",
            "  - Redesigned Settings: category sidebar, aligned rows, tooltips, live preview",
            "  - Right-click menu adds Always on top (under Lock)",
            "  - New out-of-the-box defaults (bigger clock/date/weekday, etc.)",
            "",
            "2.4.0",
            "  - Start with Windows now uses a Startup shortcut (avoids the Defender flag)",
            "  - Embedded app icon (same as tray); tray click brings the overlay to front",
            "  - Remembers window position per screen resolution",
            "  - Configurable LAN / WAN IP refresh intervals; version metadata in the exe",
            "",
            "2.3.0",
            "  - Separate download/upload colors (default green/red) for net graph + totals",
            "  - Net totals text size; centered LAN/WAN; section titles a uniform size",
            "  - Tidier drive label/bar spacing",
            "",
            "2.2.0",
            "  - Adjustable text size for Top CPU / Top RAM and IP sections",
            "  - Save current settings as defaults; Reset to defaults",
            "",
            "2.1.0",
            "  - Single instance (won't launch twice)",
            "  - Start with Windows toggle; configurable refresh interval",
            "  - GPU temp via NVIDIA NVML (no nvidia-smi process spawning)",
            "  - Lower memory churn; optional debug log",
            "  - Larger, easier-to-use Settings window; GitHub Actions build/release",
            "",
            "2.0.0",
            "  - Reorderable sections (drag order + show/hide in Settings)",
            "  - Per-graph max scale, color, and red alert threshold",
            "  - Network unit toggle (MB/s or Mbps) + session download/upload totals",
            "  - Internal + external IP; Top-5 CPU and Top-5 RAM processes",
            "  - Drives show free space, mapped network drives, sizable labels",
            "  - Date / weekday bold options; Settings centered + scrollable",
            "",
            "1.2.0",
            "  - Settings dialog: window width, graph height, drive bar height",
            "  - Show / hide each section",
            "  - Clock / date / weekday: size, color and a seconds toggle",
            "  - Drive usage bars (This PC style)",
            "  - Lock position; overlay vs background (normal window) mode",
            "  - About dialog",
            "",
            "1.1.0",
            "  - Clock, per-drive capacity, date and weekday",
            "  - Best-effort temperatures (ACPI CPU, nvidia-smi GPU)",
            "  - Network graph auto-scaling",
            "",
            "1.0.0",
            "  - Initial overlay: CPU, GPU, RAM, disk and network graphs",
        };
    }
}
